// Product Database - Sneaker Labs
const products = [
    {
        id: 1,
        name: "Ultra Runner X1",
        category: "running",
        price: 189.00,
        originalPrice: 189.00,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500",
        description: "Advanced cushioning technology with responsive foam",
        fullDescription: "Experience next-level performance with our Ultra Runner X1. Featuring advanced responsive foam, breathable mesh upper, and ergonomic design for marathon runners.",
        rating: 4.8,
        reviews: 156,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white", "gray"],
        badge: "NEW"
    },
    {
        id: 2,
        name: "Street Lab Pro",
        category: "casual",
        price: 145.00,
        originalPrice: 145.00,
        image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=500&h=500",
        description: "Urban minimalist design with premium materials",
        fullDescription: "Perfect for everyday wear, the Street Lab Pro combines urban aesthetics with comfort. Premium leather upper with reinforced stitching.",
        rating: 4.7,
        reviews: 234,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white"],
        badge: ""
    },
    {
        id: 3,
        name: "Apex Performance",
        category: "basketball",
        price: 199.00,
        originalPrice: 249.00,
        image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&h=500",
        description: "Pro-level basketball performance shoe",
        fullDescription: "Engineered for basketball excellence with ankle support, responsive midsole, and secure lockdown system for competitive play.",
        rating: 4.9,
        reviews: 189,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white", "gray"],
        badge: "SALE"
    },
    {
        id: 4,
        name: "Future Flow",
        category: "futuristic",
        price: 225.00,
        originalPrice: 225.00,
        image: "https://images.unsplash.com/photo-1520454041899-490289f7aa55?w=500&h=500",
        description: "Futuristic silhouette with tech-wear aesthetics",
        fullDescription: "Breaking boundaries with innovative design. Ultra-lightweight knit upper, 3D-printed heel counter, and dynamic color blocking.",
        rating: 4.6,
        reviews: 142,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white", "gray"],
        badge: "NEW"
    },
    {
        id: 5,
        name: "Classic Lab Limited",
        category: "casual",
        price: 179.00,
        originalPrice: 179.00,
        image: "https://images.unsplash.com/photo-1525162a4d4e4b12fc13999fc8ce3ecd0aae4618?w=500&h=500",
        description: "Timeless silhouette with modern updates",
        fullDescription: "A modern take on a classic design. Canvas upper with leather accents, gum sole, perfect for any occasion.",
        rating: 5.0,
        reviews: 298,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white"],
        badge: "BESTSELLER"
    },
    {
        id: 6,
        name: "Trail Blazer Elite",
        category: "outdoor",
        price: 229.00,
        originalPrice: 279.00,
        image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&h=500",
        description: "Premium trail running with all-terrain grip",
        fullDescription: "Designed for rugged terrain. Waterproof gore-tex lining, aggressive tread pattern, and reinforced toe cap for durability.",
        rating: 4.7,
        reviews: 167,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "gray"],
        badge: "SALE"
    },
    {
        id: 7,
        name: "Monochrome Zero",
        category: "casual",
        price: 135.00,
        originalPrice: 135.00,
        image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&h=500",
        description: "Minimalist pure white design",
        fullDescription: "The ultimate minimalist statement. Pure white leather construction with black minimal branding. Perfect for clean aesthetics.",
        rating: 4.9,
        reviews: 445,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["white"],
        badge: ""
    },
    {
        id: 8,
        name: "Midnight Edition",
        category: "casual",
        price: 155.00,
        originalPrice: 155.00,
        image: "https://images.unsplash.com/photo-1502489881917-04fce69fadba?w=500&h=500",
        description: "All-black premium silhouette",
        fullDescription: "Sleek all-black design with premium suede and leather mix. Perfect for dark streetwear aesthetic and formal settings.",
        rating: 4.8,
        reviews: 312,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black"],
        badge: ""
    },
    {
        id: 9,
        name: "City Runner",
        category: "running",
        price: 165.00,
        originalPrice: 165.00,
        image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&h=500",
        description: "Urban running with retro vibes",
        fullDescription: "Retro-inspired running shoe for city streets. Cushioned midsole, lightweight design, and timeless coloring.",
        rating: 4.5,
        reviews: 198,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white", "gray"],
        badge: ""
    },
    {
        id: 10,
        name: "Grid Max",
        category: "basketball",
        price: 219.00,
        originalPrice: 219.00,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500",
        description: "Experimental grid pattern design",
        fullDescription: "Cutting-edge basketball shoe with experimental grid pattern. Enhanced ankle support and lightweight breathable mesh.",
        rating: 4.7,
        reviews: 276,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "gray"],
        badge: "NEW"
    },
    {
        id: 11,
        name: "Echo Lab Retro",
        category: "casual",
        price: 175.00,
        originalPrice: 225.00,
        image: "https://images.unsplash.com/photo-1505228395891-9a51e7e86e81?w=500&h=500",
        description: "Retro silhouette with modern tech",
        fullDescription: "Vintage-inspired design with contemporary cushioning. Perfect blend of nostalgia and modern comfort.",
        rating: 4.9,
        reviews: 389,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white"],
        badge: "SALE"
    },
    {
        id: 12,
        name: "Prototype X",
        category: "futuristic",
        price: 299.00,
        originalPrice: 349.00,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500",
        description: "Experimental prototype with aerospace tech",
        fullDescription: "Limited edition experimental design. Features aerospace-grade materials, 3D-knit upper, and reactive sole technology.",
        rating: 5.0,
        reviews: 87,
        sizes: ["6", "7", "8", "9", "10", "11", "12", "13"],
        colors: ["black", "white", "gray"],
        badge: "BESTSELLER"
    }
];

// Promo Codes
const promoCodes = {
    "LABS10": 0.10,
    "LABS20": 0.20,
    "SNEAKER": 0.15,
    "WELCOME": 0.25
};


