// Product Database - Sneaker Labs
const products = [
    {
        id: 1,
        name: "Ultra Runner X1",
        category: "running",
        price: 189.00,
        originalPrice: 189.00,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop",
        description: "Advanced technology with comfortable foam",
        fullDescription: "Experience next-level performance with our Ultra Runner X1. Featuring advanced responsive foam, breathable mesh upper, and ergonomic design for marathon runners.",
        rating: 4.8,
        reviews: 156,
        sizes: ["38", "39", "40"],
        colors: ["black", "white", "gray"],
        badge: "NEW"
    },
    {
        id: 2,
        name: "Street Lab Pro",
        category: "casual",
        price: 145.00,
        originalPrice: 145.00,
        image: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=500&h=500&fit=crop",
        description: "Urban minimalist design with premium materials",
        fullDescription: "Perfect for everyday wear, the Street Lab Pro combines urban aesthetics with comfort. Premium leather upper with reinforced stitching.",
        rating: 4.7,
        reviews: 234,
        sizes: ["38", "39", "40"],
        colors: ["black", "white"],
        badge: ""
    },
    {
        id: 3,
        name: "Apex Performance",
        category: "basketball",
        price: 199.00,
        originalPrice: 249.00,
        image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&h=500&fit=crop",
        description: "Pro-level basketball performance shoe",
        fullDescription: "Engineered for basketball excellence with ankle support, responsive midsole, and secure lockdown system for competitive play.",
        rating: 4.9,
        reviews: 189,
        sizes: ["38", "39", "40"],
        colors: ["black", "white", "gray"],
        badge: "SALE"
    },
    {
        id: 4,
        name: "Future Flow",
        category: "futuristic",
        price: 225.00,
        originalPrice: 225.00,
        image: "future lab.png",
        description: "Futuristic silhouette with tech-wear aesthetics",
        fullDescription: "Breaking boundaries with innovative design. Ultra-lightweight knit upper, 3D-printed heel counter, and dynamic color blocking.",
        rating: 4.6,
        reviews: 142,
        sizes: ["38", "39", "40"],
        colors: ["black", "white", "gray"],
        badge: "NEW"
    },
    {
        id: 5,
        name: "Classic Lab Limited",
        category: "casual",
        price: 179.00,
        originalPrice: 179.00,
        image: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=500&h=500&fit=crop",
        description: "Timeless silhouette with modern updates",
        fullDescription: "A modern take on a classic design. Canvas upper with leather accents, gum sole, perfect for any occasion.",
        rating: 5.0,
        reviews: 298,
        sizes: ["38", "39", "40"],
        colors: ["black", "white"],
        badge: "BESTSELLER"
    },
    {
        id: 6,
        name: "Trail Blazer Elite",
        category: "outdoor",
        price: 229.00,
        originalPrice: 279.00,
        image: "https://images.unsplash.com/photo-1570637788417-0e82375c9371?w=500&h=500&fit=crop",
        description: "Premium trail running with all-terrain grip",
        fullDescription: "Designed for rugged terrain. Waterproof gore-tex lining, aggressive tread pattern, and reinforced toe cap for durability.",
        rating: 4.7,
        reviews: 167,
        sizes: ["38", "39", "40"],
        colors: ["black", "gray"],
        badge: "SALE"
    },
    {
        id: 7,
        name: "Monochrome Zero",
        category: "casual",
        price: 135.00,
        originalPrice: 135.00,
        image: "https://images.unsplash.com/photo-1525162a4d4e4b12fc13999fc8ce3ecd0aae4618?w=500&h=500&fit=crop",
        description: "Minimalist pure white design",
        fullDescription: "The ultimate minimalist statement. Pure white leather construction with black minimal branding. Perfect for clean aesthetics.",
        rating: 4.9,
        reviews: 445,
        sizes: ["38", "39", "40"],
        colors: ["white"],
        badge: ""
    },
    {
        id: 8,
        name: "Midnight Edition",
        category: "casual",
        price: 155.00,
        originalPrice: 155.00,
        image: "https://images.unsplash.com/photo-1595777712802-bbb887cc5fa9?w=500&h=500&fit=crop",
        description: "All-black premium silhouette",
        fullDescription: "Sleek all-black design with premium suede and leather mix. Perfect for dark streetwear aesthetic and formal settings.",
        rating: 4.8,
        reviews: 312,
        sizes: ["38", "39", "40"],
        colors: ["black"],
        badge: ""
    },
    {
        id: 9,
        name: "City Runner",
        category: "running",
        price: 165.00,
        originalPrice: 165.00,
        image: "city.png",
        description: "Urban running with retro vibes",
        fullDescription: "Retro-inspired running shoe for city streets. Cushioned midsole, lightweight design, and timeless coloring.",
        rating: 4.5,
        reviews: 198,
        sizes: ["38", "39", "40"],
        colors: ["black", "white", "gray"],
        badge: ""
    },
    {
        id: 10,
        name: "Grid Max",
        category: "basketball",
        price: 219.00,
        originalPrice: 219.00,
        image: "grid.png",
        description: "Experimental grid pattern design",
        fullDescription: "Cutting-edge basketball shoe with experimental grid pattern. Enhanced ankle support and lightweight breathable mesh.",
        rating: 4.7,
        reviews: 276,
        sizes: ["38", "39", "40"],
        colors: ["black", "gray"],
        badge: "NEW"
    },
    {
        id: 11,
        name: "Echo Lab Retro",
        category: "casual",
        price: 175.00,
        originalPrice: 225.00,
        image: "echo.png",
        description: "Retro silhouette with modern tech",
        fullDescription: "Vintage-inspired design with contemporary cushioning. Perfect blend of nostalgia and modern comfort.",
        rating: 4.9,
        reviews: 389,
        sizes: ["38", "39", "40"],
        colors: ["black", "white"],
        badge: "SALE"
    },
    {
        id: 12,
        name: "Prototype X",
        category: "futuristic",
        price: 299.00,
        originalPrice: 349.00,
        image: "proto.png",
        description: "Experimental prototype with aerospace tech",
        fullDescription: "Limited edition experimental design. Features aerospace-grade materials, 3D-knit upper, and reactive sole technology.",
        rating: 5.0,
        reviews: 87,
        sizes: ["38", "39", "40"],
        colors: ["black", "white", "gray"],
        badge: "BESTSELLER"
    },
    {
        id: 13,
        name: "Lab Tech Hoodie",
        category: "apparel",
        price: 89.00,
        originalPrice: 99.00,
        image: "hoodie.png",
        description: "Fleece-lined hoodie with techwear details",
        fullDescription: "Stay warm while keeping a sleek lab aesthetic. Lightweight yet cozy with ergonomic thumbholes and zippered pockets.",
        rating: 4.8,
        reviews: 72,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["black", "gray", "white"],
        badge: "NEW"
    },
    {
        id: 14,
        name: "Velocity Tee",
        category: "apparel",
        price: 45.00,
        originalPrice: 45.00,
        image: "velo png.png",
        description: "Performance tee for everyday movement",
        fullDescription: "Soft, breathable fabric with a minimalist fit. The Velocity Tee is designed for training, layering, and city styling.",
        rating: 4.6,
        reviews: 108,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["black", "white", "beige"],
        badge: ""
    },
    {
        id: 15,
        name: "Utility Windbreaker",
        category: "apparel",
        price: 119.00,
        originalPrice: 139.00,
        image: "baju biru .png",
        description: "Lightweight shell with hidden storage",
        fullDescription: "A technical windbreaker built for urban movement. Water-resistant material with hidden pockets and adjustable hood.",
        rating: 4.7,
        reviews: 89,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["olive", "black", "gray"],
        badge: "SALE"
    }
];

// Promo Codes
const promoCodes = {
    "LABS10": 0.10,
    "LABS20": 0.20,
    "SNEAKER": 0.15,
    "WELCOME": 0.25
};


