// Product Database - Sneaker Labs
const products = [
    {
        id: 1,
        name: "NIKE AIR MAX X1",
        category: "lifestyle",
        price: 210.00,
        originalPrice: 210.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD17w52mIb2jQT3c7RtL4Xg7OZPLu5uojSUHNAdaOUXO_FWl_gD5HzvQ-4LKv4Q2ngnLYpwOnL-90dIENpw-RQJ9CR1eceDUinKaSv0Y6ckh36pVZF9l3W63jtcUys4aQLJZ8ViL2aACDZsyWgxkDslQFiVJK-cuZBzdjoTRKivipBbgIaCYWxP5H44rX__PYrWQjkWc0aIhOksVRMjSKlzHPRCib8EyTi9fG24XKI_xAYxkBqVAKNc40Daim8p70mMHdmaQbdBf-A",
        description: "A premium lifestyle sneaker built for comfort and modern performance.",
        fullDescription: "Experience next-level comfort with the Nike Air Max X1. Combining iconic Air cushioning with futuristic techwear styling, this is the ultimate daily sneaker.",
        rating: 4.9,
        reviews: 156,
        sizes: ["39", "40", "41", "42", "43", "44"],
        colors: ["black", "blue", "white"],
        badge: "BESTSELLER"
    },
    {
        id: 2,
        name: "JORDAN 1 RETRO",
        category: "basketball",
        price: 320.00,
        originalPrice: 320.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDz01j0VQ4o6_zDf2IL2uMtv5jNQigcq3Lp0ct5vTCda-D5HGG9pHIMFaGsiaw33APjDpVrcfKlo0aGIDpqiDt-71yVFm_Z2IuuDkV-x7vDAL9mY6xh--b7q2wRpt8-D6YHGwOviUc0kf8TXYpbw6G3dfpAXnwsq6TVUOZM_IP0LnPqOIGX7xwJn9PXVFQ2VGjR2A5B_CFJkuysX-7qAIXMBmCdijNZY8sgHdUOLmt39o4AgnkmqNQeJR79w6pUEema22XlPw_a820",
        description: "Classic Jordan craftsmanship with a contemporary laboratory finish.",
        fullDescription: "The Jordan 1 Retro features classic premium leather construction with an experimental design finish. Engineered for stability on-court and high-fashion off-court styling.",
        rating: 5.0,
        reviews: 234,
        sizes: ["40", "41", "42", "43", "44", "45"],
        colors: ["red", "white", "black"],
        badge: "LIMITED"
    },
    {
        id: 3,
        name: "NIKE AIR MAX ALPHA",
        category: "running",
        price: 210.00,
        originalPrice: 210.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAzYTe2ccssxDAfhJ7J5_iyEYa8_y3ZZPb4J3DVtpjoVCf0sq_wa3Q5s5IBwEVItkcHzE5ctF5PSgG9E2VnVz5OtG9AsRn7hv3rzguIUUHh1QB5KmfE0orKMdme1wmSaOiciIaMA_l-6jgUASwaIMFq-4GpjfuGf8C08wglNq2Z9duHugN6zfeVLiNC8b3WeuDuOW52CH9n1Ykz4bTQRkHBflu4Ey1tMbQ_9jsaKDYa9Uj0P13K9MnwVQEWyOa0uaEAeZLVF9QpjGk",
        description: "Performance-focused running silhouette with premium cushioning.",
        fullDescription: "Built for speed and high impact absorption, the Nike Air Max Alpha utilizes a responsive mesh outer shell and structured TPU overlay for dynamic training runs.",
        rating: 4.9,
        reviews: 189,
        sizes: ["38", "39", "40", "41", "42"],
        colors: ["gray", "blue"],
        badge: "LAB SPECIMEN"
    },
    {
        id: 4,
        name: "AIR MAX \"LAB ZERO\"",
        category: "lifestyle",
        price: 240.00,
        originalPrice: 240.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQ9dr7SvZHDB6Ud1N9EDVIe9X9IB6-AlhoSpHcYUK0Kf1b1ZkdW1gfSVx6xc3_IGytcjD0c_38I359GtK7aiSlH1eTdUeHW5SY7_KDWcSTndKdAS1e_C2FeNT13wgleZFJ7n8mx4D9DxNnVIH5u7jIb5V4cPmaYp8hLG0Aq-muAcGJxiOjXgqR57KuqWvln308p8hqZneHcLfUxjM2fLIfAFzjxwSgRZR_9fNQtmtyfHukBZhoKBoJBJht2c9bw7ljyDDIuX29fyo",
        description: "Futuristic archival prototype demonstrating maximum kinetic cushion return.",
        fullDescription: "A pure design experiment. Featuring exposed cushion nodes and a translucent upper mesh, the Lab Zero delivers maximum comfort and visibility.",
        rating: 4.9,
        reviews: 142,
        sizes: ["39", "40", "41", "42", "43", "44"],
        colors: ["blue", "white"],
        badge: "NEW"
    },
    {
        id: 5,
        name: "FORUM HIGH ARCHIVE",
        category: "basketball",
        price: 180.00,
        originalPrice: 180.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDsgguMD_wkQqbhjTqSlWeowM0TpttAxo5L8bHBzVdolGJXAllg6kkof_gW6rJm2jW_El4reZnDNhE0r40RI-tkTbwAg-qwvOTJnWpCYFByLX9PPG4JDwYyMK-FQ-oiBM4rGasKQzc79ci4OSeFrNF0CwEznhZSDXz4Sl_ixrnHx4w9XyPEu12RUZXGxlDmig4Msm--yNFdT_NV0mtf1fVGQ8IKzG9SOya83TsXXrDcfRKedu-HeLGBY1rMQWXinFR0mD5CPoDa7tk",
        description: "Classic basketball model updated with premium modern leather specs.",
        fullDescription: "An Adidas original, reworked with premium leather panelling and contrast strap design. Delivers lockdown performance with a strong retro aesthetic.",
        rating: 4.8,
        reviews: 298,
        sizes: ["40", "41", "42", "43"],
        colors: ["white", "black"],
        badge: "NEW"
    },
    {
        id: 6,
        name: "990v6 PROTOTYPE",
        category: "running",
        price: 220.00,
        originalPrice: 220.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAkrjjcoqd0DYa02z3mvS7ky8QP2OXvQ4YmwwnR6qPXSI0V9dcUu0ADcZ1NFBampjOkH8cp0ihExfNl3MDRSgO540Wpj52nZvgwoYzjiLKfPldKdMNxsFhzLQRD824dr_Uu-dqXYB5S7Fkbiu-phc9UY7w1r8rsPTgRTisBnazO8EOVLEc-FJLA_1Tab2g419jw461H5J6S9K4-tCE4Ma3NQyKuHr9y1CzTBsHyRpSmm76_EEUyO3_UvxApNXljqdp4S6xnJfFJUFU",
        description: "Highly optimized running specimen engineered for clinical distance performance.",
        fullDescription: "New Balance's performance peak. Utilizing FuelCell foam core technology and reflective carbon plates, the 990v6 provides unparalleled support over long-distance runs.",
        rating: 4.9,
        reviews: 167,
        sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
        colors: ["gray", "white"],
        badge: "NEW"
    },
    {
        id: 7,
        name: "RETRO HIGH \"LAB SLATE\"",
        category: "basketball",
        price: 190.00,
        originalPrice: 190.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1EHx_HkXg9qTxXYZrjt-zfUtOcx-n-_QBPLTqKWb5ONEIGl0ztH5GOqGbTGSqgiqDuMt_aD-ObskZyn_0Djywpkj0bWOvarCPlvsd-W98pDTzh0vg-hNSICvxqC5t0M9ZB9QScfXFc2WaHoJuQIS9BHG7SOFF2hg0orhy7WM8i3jCQtCCqeBtoXuVqpKhnsZ0-c7P3o1iPejK6VBJddgLFIbRc4L07cMYTXYQ8AVki0zxZgHShcY3mKpuY-nhUX936Q4Z6bUCl8A",
        description: "Deep archival release featuring technical nubuck overlay styling.",
        fullDescription: "The ultimate streetwear classic. Made from heavy-weight nubuck leather overlays with a clinical slate grey and black finish.",
        rating: 5.0,
        reviews: 445,
        sizes: ["41", "42", "43", "44", "45"],
        colors: ["black", "gray"],
        badge: "NEW"
    },
    {
        id: 8,
        name: "ADIDAS ALPHA FLY",
        category: "running",
        price: 260.00,
        originalPrice: 260.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIiDNIOJ_jn3LoqX9FoP2cedS4wX0EwQtQ6MVexER3YglIwcX6v8AIN9IN3rdPPa02XxdOJqGeE2vjCyI9Fj21kCJb46YoJCdSQpGEOk8Qbqgf0xN0-1YekZ6jxSWcxE8SGm5Qm_i9DxfowiAg5l0tr0VSRGgCOK28jFpYKFtIXx1QjuBUSLYT5wLYqrDazG8B_X4ZYFWg6S_g75bZtzHgdNeVJrXlgYvqTugFDh-cQ4ssjjA9f1w9ycRi53Moe3PF4wDnEZtgWlc",
        description: "Ultra-marathon specialized kinetic hardware designed for raw speed.",
        fullDescription: "Engineered specifically to break marathon records. Dual carbon plates combined with responsive ZoomX-style foam cells deliver maximal energy return.",
        rating: 4.8,
        reviews: 312,
        sizes: ["39", "40", "41", "42", "43", "44"],
        colors: ["blue", "black", "white"],
        badge: "HOT"
    },
    {
        id: 9,
        name: "NB VAPORWAVE",
        category: "lifestyle",
        price: 150.00,
        originalPrice: 150.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC2bEWf_rhsSXNoevWvUQBe2RMKa3PV3yWsvrO2B3RpGSeYSGXFrpz2_-GsHqnSmbiUF2j956bJ4hxHXoLt_F92gCMzn-CYzTa0FmOg_dXwQKGwFgUPGXmqmQrh2UhmYCQ8gqEc32er_ylfP7ocHyk0I6-rc6s8kXWY8uVdsR1-B1lZAvdeTnqGHRr9MVy8ThibujYADwPAA4IdqVZ11jfTWXTHGU7k5YxpMJjO1HVvWQGmBOsKpEB2r3ga_7UTxHC4BCxxOuL80pc",
        description: "Vaporwave aesthetics combined with comfortable multi-density foam core.",
        fullDescription: "A lifestyle runner inspired by 80s vaporwave color palettes. Multi-density foam core ensures support and clean styling for city exploring.",
        rating: 4.6,
        reviews: 198,
        sizes: ["38", "39", "40", "41", "42"],
        colors: ["gray", "blue", "white"],
        badge: "POPULAR"
    },
    {
        id: 10,
        name: "CYBER RUNNER",
        category: "running",
        price: 280.00,
        originalPrice: 280.00,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCkZvT1dDEM48zlPR0m52OlweHnzrQYXT76WRlj5BEaRj1vtz3xvCpARmaV9jeeuiVRdmICdT6Kn1euHQcPlGZGAVsyG0dnzgRLxpETik5qtwWL8szkD8IUBlM8XLYVdkkdobmCrcRZQFVmtW11hYLkfpl8j6KAjr7BjAEgddVN-d0NNLYDsYI9cjKU9a11RRFnQsPAaoVcShEea6ezh_AXzR38Yh-L8kEmNxthXgujoguwV_PE9WGz4v70s-Hbz56rcyzxVN_uRsc",
        description: "Cyberpunk inspired shell featuring modular support units and reflective overlays.",
        fullDescription: "Futuristic techwear at its best. Built with reflective outer plates, high-tensile mesh, and magnetic strap locks.",
        rating: 4.9,
        reviews: 276,
        sizes: ["40", "41", "42", "43", "44", "45"],
        colors: ["black", "red", "gray"],
        badge: "NEW"
    },
    {
        id: 11,
        name: "ADIDAS YEEZY 350 BOOST",
        category: "lifestyle",
        price: 220.00,
        originalPrice: 250.00,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop",
        description: "Iconic Primeknit upper with Boost cushioning.",
        fullDescription: "The Yeezy Boost 350 combines iconic Primeknit material with Adidas' full-length Boost sole. A streetwear legend engineered for everyday comfort.",
        rating: 4.8,
        reviews: 320,
        sizes: ["38", "39", "40", "41", "42", "43", "44"],
        colors: ["black", "gray", "white"],
        badge: "SALE"
    },
    {
        id: 12,
        name: "NIKE DUNKS LOW PRO",
        category: "lifestyle",
        price: 110.00,
        originalPrice: 110.00,
        image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500&h=500&fit=crop",
        description: "Skateboard-inspired low-top classic.",
        fullDescription: "The Nike Dunk Low Pro remains a staple. Clean color panelling, comfortable ankle collar, and rubber outsole for everyday skating or lifestyle wear.",
        rating: 4.7,
        reviews: 412,
        sizes: ["38", "39", "40", "41", "42", "43", "44"],
        colors: ["black", "white"],
        badge: "POPULAR"
    },
    {
        id: 13,
        name: "LAB TECH HOODIE",
        category: "apparel",
        price: 89.00,
        originalPrice: 99.00,
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&h=500&fit=crop",
        description: "Fleece-lined hoodie with techwear details.",
        fullDescription: "Heavy-weight technical hoodie engineered for everyday wear. Fleece lining, zip-pockets, and water-repellent panels.",
        rating: 4.8,
        reviews: 72,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["black", "gray", "white"],
        badge: "NEW"
    },
    {
        id: 14,
        name: "VELOCITY TEE",
        category: "apparel",
        price: 45.00,
        originalPrice: 45.00,
        image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&h=500&fit=crop",
        description: "Performance tee for everyday movement.",
        fullDescription: "Breathable cotton-blend performance tee featuring a drop-shoulder cut and minimal branding.",
        rating: 4.6,
        reviews: 108,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["black", "white", "beige"],
        badge: ""
    },
    {
        id: 15,
        name: "UTILITY WINDBREAKER",
        category: "apparel",
        price: 119.00,
        originalPrice: 139.00,
        image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=500&h=500&fit=crop",
        description: "Lightweight shell with hidden storage.",
        fullDescription: "A weather-resistant technical windbreaker. Features adjustable elastic cuffs, storm hoods, and hidden front pockets.",
        rating: 4.7,
        reviews: 89,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["black", "gray"],
        badge: "SALE"
    }
];

// Promo Codes
const promoCodes = {
    "LABS10": 0.10,
    "LABS20": 0.20,
    "SNEAKER": 0.15,
    "WELCOME": 0.25
};

window.products = products;
